services:
  youtube-transcript-api:
    build: .
    container_name: youtube-transcript-api
    restart: always
    ports:
      - "127.0.0.1:8084:8084"
    environment:
      - PORT=8084
      - HOST=0.0.0.0